using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Demo3.Migrations.Postgresql.Migrations
{
    public partial class CreateDb : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Actors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Actors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Productions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: true),
                    Release = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    Discriminator = table.Column<string>(type: "text", nullable: false),
                    DurationInMinutes = table.Column<int>(type: "integer", nullable: true),
                    WorldwideBoxOfficeGross = table.Column<double>(type: "double precision", nullable: true),
                    NumberOfEpisodes = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Productions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Characters",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ProductionId = table.Column<int>(type: "integer", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: true),
                    ActorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Characters", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Characters_Actors_ActorId",
                        column: x => x.ActorId,
                        principalTable: "Actors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Characters_Productions_ProductionId",
                        column: x => x.ProductionId,
                        principalTable: "Productions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Ratings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ProductionId = table.Column<int>(type: "integer", nullable: false),
                    Source = table.Column<string>(type: "text", nullable: true),
                    Stars = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Ratings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Ratings_Productions_ProductionId",
                        column: x => x.ProductionId,
                        principalTable: "Productions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Actors",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Robert Downey Jr." },
                    { 18, "Melissa McBride" },
                    { 17, "Norman Reedus" },
                    { 16, "Hazuki Shimizu" },
                    { 15, "Matsuya Onoe" },
                    { 13, "Winona Ryder" },
                    { 12, "Caleb McLaughlin" },
                    { 11, "Millie Bobby Brown" },
                    { 10, "Karyn Parsons" },
                    { 14, "David Harbour" },
                    { 8, "Maggie Smith" },
                    { 7, "Will Smith" },
                    { 6, "Donny Yen" },
                    { 5, "Beyoncé" },
                    { 4, "Donald Glover" },
                    { 3, "Danai Guira" },
                    { 2, "Chris Evans" },
                    { 9, "Michelle Dockery" }
                });

            migrationBuilder.InsertData(
                table: "Productions",
                columns: new[] { "Id", "Discriminator", "Name", "NumberOfEpisodes", "Release" },
                values: new object[,]
                {
                    { 8, "Series", "Stranger Things", 34, new DateTime(2016, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 7, "Series", "Downton Abbey", 52, new DateTime(2010, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 6, "Series", "The Fresh Prince of Bel-Air", 148, new DateTime(1990, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.InsertData(
                table: "Productions",
                columns: new[] { "Id", "Discriminator", "DurationInMinutes", "Name", "Release", "WorldwideBoxOfficeGross" },
                values: new object[,]
                {
                    { 5, "Movie", 120, "Downton Abbey", new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 194051302.0 },
                    { 1, "Movie", 181, "Avengers: Endgame", new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), 2797800564.0 },
                    { 3, "Movie", 105, "Ip Man 4", new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), 192617891.0 },
                    { 2, "Movie", 118, "The Lion King", new DateTime(2019, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), 1654791102.0 }
                });

            migrationBuilder.InsertData(
                table: "Productions",
                columns: new[] { "Id", "Discriminator", "Name", "NumberOfEpisodes", "Release" },
                values: new object[] { 9, "Series", "Kantaro: The Sweet Tooth Salaryman", 12, new DateTime(2017, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified) });

            migrationBuilder.InsertData(
                table: "Productions",
                columns: new[] { "Id", "Discriminator", "DurationInMinutes", "Name", "Release", "WorldwideBoxOfficeGross" },
                values: new object[] { 4, "Movie", 116, "Gemini Man", new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), 166623705.0 });

            migrationBuilder.InsertData(
                table: "Productions",
                columns: new[] { "Id", "Discriminator", "Name", "NumberOfEpisodes", "Release" },
                values: new object[] { 10, "Series", "The Walking Dead", 177, new DateTime(2010, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified) });

            migrationBuilder.InsertData(
                table: "Characters",
                columns: new[] { "Id", "ActorId", "Name", "ProductionId" },
                values: new object[,]
                {
                    { 1, 1, "Tony Stark", 1 },
                    { 6, 6, "Ip Man", 3 },
                    { 7, 7, "Henry Brogan", 4 },
                    { 8, 8, "Violet Crawley", 5 },
                    { 9, 9, "Lady Mary Crawley", 5 },
                    { 10, 7, "Will Smith", 6 },
                    { 12, 8, "Violet Crawley", 7 },
                    { 13, 9, "Lady Mary Crawley", 7 },
                    { 5, 5, "Nala", 2 },
                    { 14, 11, "Eleven", 8 },
                    { 16, 13, "Joyce Byers", 8 },
                    { 17, 14, "Jim Hopper", 8 },
                    { 18, 15, "Ametani Kantarou", 9 },
                    { 19, 16, "Sano Erika", 9 },
                    { 20, 17, "Daryl Dixon", 10 },
                    { 21, 3, "Michonne", 10 },
                    { 22, 18, "Carol Peletier", 10 },
                    { 15, 12, "Lucas", 8 },
                    { 4, 4, "Simba", 2 },
                    { 11, 10, "Hilary Banks", 6 },
                    { 2, 2, "Steve Rogers", 1 },
                    { 3, 3, "Okoye", 1 }
                });

            migrationBuilder.InsertData(
                table: "Ratings",
                columns: new[] { "Id", "ProductionId", "Source", "Stars" },
                values: new object[,]
                {
                    { 18, 1, "Magazine", 4 },
                    { 666, 7, "Magazine", 4 },
                    { 667, 7, "Newspaper", 4 },
                    { 668, 7, "Newspaper", 5 },
                    { 669, 7, "Magazine", 3 },
                    { 670, 7, "Newspaper", 5 },
                    { 671, 7, "Internet", 2 },
                    { 672, 7, "Magazine", 3 },
                    { 673, 7, "Magazine", 3 },
                    { 674, 7, "Newspaper", 2 },
                    { 675, 7, "App", 3 },
                    { 676, 7, "Newspaper", 2 },
                    { 665, 7, "Magazine", 2 },
                    { 677, 7, "Internet", 4 },
                    { 679, 7, "Magazine", 2 },
                    { 680, 7, "Magazine", 1 },
                    { 681, 7, "App", 1 },
                    { 682, 7, "Internet", 1 },
                    { 683, 7, "Magazine", 5 },
                    { 684, 7, "Newspaper", 1 },
                    { 685, 7, "App", 3 },
                    { 686, 7, "Internet", 5 },
                    { 687, 7, "Newspaper", 4 },
                    { 688, 7, "App", 2 },
                    { 689, 7, "App", 5 },
                    { 690, 7, "Magazine", 1 },
                    { 691, 7, "Magazine", 2 },
                    { 678, 7, "Internet", 2 },
                    { 664, 7, "Newspaper", 5 },
                    { 663, 7, "Magazine", 1 },
                    { 662, 7, "Magazine", 3 },
                    { 636, 7, "Magazine", 4 },
                    { 637, 7, "Newspaper", 2 },
                    { 638, 7, "Magazine", 4 },
                    { 639, 7, "Newspaper", 1 },
                    { 640, 7, "Newspaper", 4 },
                    { 641, 7, "App", 2 },
                    { 642, 7, "Internet", 5 },
                    { 643, 7, "Magazine", 3 },
                    { 644, 7, "Internet", 3 },
                    { 645, 7, "App", 1 },
                    { 646, 7, "Internet", 2 },
                    { 647, 7, "Internet", 4 },
                    { 692, 7, "Newspaper", 4 },
                    { 648, 7, "Internet", 2 },
                    { 650, 7, "Internet", 5 },
                    { 651, 7, "App", 3 },
                    { 652, 7, "Newspaper", 2 },
                    { 653, 7, "Internet", 2 },
                    { 654, 7, "Newspaper", 2 },
                    { 655, 7, "Magazine", 4 },
                    { 656, 7, "Magazine", 2 },
                    { 657, 7, "Newspaper", 4 },
                    { 658, 7, "Newspaper", 3 },
                    { 659, 7, "Magazine", 4 },
                    { 660, 7, "Magazine", 5 },
                    { 661, 7, "Newspaper", 1 },
                    { 649, 7, "Magazine", 1 },
                    { 693, 7, "Newspaper", 2 },
                    { 694, 7, "Newspaper", 5 },
                    { 695, 7, "Magazine", 2 },
                    { 725, 8, "App", 2 },
                    { 726, 8, "Magazine", 5 },
                    { 727, 8, "Newspaper", 2 },
                    { 728, 8, "Internet", 3 },
                    { 729, 8, "App", 1 },
                    { 730, 8, "Internet", 1 },
                    { 731, 8, "App", 5 },
                    { 732, 8, "Internet", 3 },
                    { 733, 8, "Internet", 1 },
                    { 734, 8, "Magazine", 5 },
                    { 735, 8, "Internet", 5 },
                    { 736, 8, "Newspaper", 4 },
                    { 737, 8, "Internet", 5 },
                    { 738, 8, "App", 3 },
                    { 739, 8, "Internet", 4 },
                    { 740, 8, "Internet", 2 },
                    { 741, 8, "App", 2 },
                    { 742, 8, "App", 4 },
                    { 743, 8, "Newspaper", 4 },
                    { 744, 8, "Newspaper", 3 },
                    { 745, 8, "Internet", 1 },
                    { 746, 8, "Internet", 2 },
                    { 747, 8, "Magazine", 1 },
                    { 748, 8, "Newspaper", 2 },
                    { 749, 8, "Magazine", 3 },
                    { 750, 8, "Internet", 3 },
                    { 751, 8, "App", 1 },
                    { 724, 8, "App", 3 },
                    { 723, 8, "App", 3 },
                    { 722, 8, "Magazine", 4 },
                    { 721, 8, "Internet", 2 },
                    { 696, 7, "App", 2 },
                    { 697, 7, "Newspaper", 3 },
                    { 698, 7, "Newspaper", 2 },
                    { 699, 7, "Newspaper", 1 },
                    { 7, 1, "Magazine", 2 },
                    { 6, 1, "App", 2 },
                    { 5, 1, "Magazine", 4 },
                    { 4, 1, "Newspaper", 1 },
                    { 701, 8, "App", 4 },
                    { 702, 8, "Internet", 3 },
                    { 703, 8, "Magazine", 5 },
                    { 704, 8, "Internet", 5 },
                    { 705, 8, "Internet", 3 },
                    { 635, 7, "Newspaper", 3 },
                    { 706, 8, "Newspaper", 5 },
                    { 708, 8, "Magazine", 3 },
                    { 709, 8, "Magazine", 3 },
                    { 710, 8, "App", 1 },
                    { 711, 8, "Magazine", 5 },
                    { 712, 8, "Magazine", 5 },
                    { 713, 8, "App", 5 },
                    { 714, 8, "Internet", 4 },
                    { 715, 8, "Magazine", 4 },
                    { 716, 8, "App", 1 },
                    { 717, 8, "Magazine", 4 },
                    { 718, 8, "Newspaper", 2 },
                    { 719, 8, "Internet", 5 },
                    { 720, 8, "Internet", 4 },
                    { 707, 8, "Internet", 2 },
                    { 634, 7, "Magazine", 2 },
                    { 632, 7, "Newspaper", 5 },
                    { 752, 8, "Internet", 1 },
                    { 544, 6, "Internet", 4 },
                    { 545, 6, "Internet", 4 },
                    { 546, 6, "Internet", 1 },
                    { 547, 6, "App", 1 },
                    { 548, 6, "App", 4 },
                    { 549, 6, "Newspaper", 2 },
                    { 550, 6, "Magazine", 2 },
                    { 551, 6, "App", 5 },
                    { 552, 6, "Newspaper", 5 },
                    { 553, 6, "Internet", 5 },
                    { 554, 6, "Magazine", 1 },
                    { 555, 6, "Internet", 5 },
                    { 556, 6, "App", 5 },
                    { 557, 6, "Newspaper", 5 },
                    { 558, 6, "App", 3 },
                    { 559, 6, "App", 5 },
                    { 560, 6, "Newspaper", 3 },
                    { 561, 6, "Magazine", 1 },
                    { 562, 6, "Internet", 2 },
                    { 563, 6, "App", 4 },
                    { 564, 6, "Magazine", 5 },
                    { 565, 6, "Magazine", 5 },
                    { 566, 6, "Newspaper", 5 },
                    { 567, 6, "Internet", 4 },
                    { 568, 6, "Internet", 5 },
                    { 569, 6, "App", 3 },
                    { 570, 6, "Magazine", 5 },
                    { 543, 6, "Internet", 5 },
                    { 571, 6, "Internet", 1 },
                    { 542, 6, "App", 2 },
                    { 540, 6, "App", 5 },
                    { 513, 6, "Internet", 3 },
                    { 514, 6, "Magazine", 3 },
                    { 515, 6, "Internet", 3 },
                    { 516, 6, "App", 4 },
                    { 517, 6, "Internet", 3 },
                    { 518, 6, "App", 4 },
                    { 519, 6, "Newspaper", 5 },
                    { 520, 6, "App", 3 },
                    { 521, 6, "Internet", 1 },
                    { 522, 6, "App", 4 },
                    { 523, 6, "Magazine", 4 },
                    { 524, 6, "Internet", 1 },
                    { 525, 6, "App", 2 },
                    { 526, 6, "Magazine", 2 },
                    { 527, 6, "Newspaper", 1 },
                    { 528, 6, "Magazine", 2 },
                    { 529, 6, "App", 5 },
                    { 530, 6, "Magazine", 2 },
                    { 531, 6, "Newspaper", 1 },
                    { 532, 6, "Newspaper", 4 },
                    { 533, 6, "App", 3 },
                    { 534, 6, "Internet", 4 },
                    { 535, 6, "App", 2 },
                    { 536, 6, "Internet", 5 },
                    { 537, 6, "Magazine", 3 },
                    { 538, 6, "Internet", 3 },
                    { 539, 6, "App", 4 },
                    { 541, 6, "Newspaper", 1 },
                    { 633, 7, "Magazine", 1 },
                    { 572, 6, "Magazine", 2 },
                    { 574, 6, "App", 1 },
                    { 605, 7, "Newspaper", 3 },
                    { 606, 7, "Magazine", 5 },
                    { 607, 7, "App", 1 },
                    { 608, 7, "Internet", 5 },
                    { 609, 7, "Internet", 2 },
                    { 610, 7, "Newspaper", 5 },
                    { 611, 7, "App", 4 },
                    { 612, 7, "Magazine", 3 },
                    { 613, 7, "App", 2 },
                    { 614, 7, "Magazine", 4 },
                    { 615, 7, "Internet", 5 },
                    { 616, 7, "Newspaper", 1 },
                    { 617, 7, "Newspaper", 2 },
                    { 618, 7, "Newspaper", 2 },
                    { 619, 7, "Magazine", 3 },
                    { 620, 7, "Magazine", 4 },
                    { 621, 7, "App", 4 },
                    { 622, 7, "App", 5 },
                    { 623, 7, "App", 4 },
                    { 624, 7, "App", 3 },
                    { 625, 7, "App", 5 },
                    { 626, 7, "Magazine", 4 },
                    { 627, 7, "Newspaper", 4 },
                    { 628, 7, "Newspaper", 2 },
                    { 629, 7, "Newspaper", 1 },
                    { 630, 7, "Magazine", 5 },
                    { 631, 7, "Magazine", 2 },
                    { 604, 7, "App", 3 },
                    { 573, 6, "Internet", 1 },
                    { 603, 7, "App", 3 },
                    { 601, 7, "Magazine", 2 },
                    { 575, 6, "App", 2 },
                    { 576, 6, "Newspaper", 5 },
                    { 577, 6, "Internet", 5 },
                    { 578, 6, "Newspaper", 3 },
                    { 579, 6, "App", 3 },
                    { 580, 6, "Internet", 4 },
                    { 581, 6, "Newspaper", 1 },
                    { 582, 6, "Newspaper", 3 },
                    { 583, 6, "Magazine", 2 },
                    { 584, 6, "App", 2 },
                    { 585, 6, "Newspaper", 2 },
                    { 586, 6, "Internet", 3 },
                    { 587, 6, "Magazine", 5 },
                    { 588, 6, "App", 1 },
                    { 589, 6, "Magazine", 2 },
                    { 590, 6, "Magazine", 5 },
                    { 591, 6, "Internet", 5 },
                    { 592, 6, "Internet", 3 },
                    { 593, 6, "Newspaper", 4 },
                    { 594, 6, "Magazine", 2 },
                    { 595, 6, "Magazine", 3 },
                    { 596, 6, "Magazine", 4 },
                    { 597, 6, "App", 1 },
                    { 598, 6, "App", 3 },
                    { 599, 6, "App", 4 },
                    { 9, 1, "Magazine", 2 },
                    { 8, 1, "Magazine", 4 },
                    { 602, 7, "Internet", 5 },
                    { 753, 8, "Magazine", 1 },
                    { 754, 8, "Internet", 5 },
                    { 755, 8, "Magazine", 5 },
                    { 910, 10, "App", 5 },
                    { 911, 10, "Magazine", 3 },
                    { 912, 10, "Magazine", 1 },
                    { 913, 10, "Magazine", 1 },
                    { 914, 10, "App", 4 },
                    { 915, 10, "Internet", 5 },
                    { 916, 10, "Magazine", 4 },
                    { 917, 10, "Magazine", 3 },
                    { 918, 10, "Internet", 1 },
                    { 919, 10, "Internet", 5 },
                    { 920, 10, "App", 4 },
                    { 921, 10, "App", 3 },
                    { 909, 10, "Magazine", 2 },
                    { 922, 10, "Magazine", 2 },
                    { 924, 10, "App", 2 },
                    { 925, 10, "Magazine", 1 },
                    { 926, 10, "Internet", 1 },
                    { 927, 10, "Magazine", 1 },
                    { 928, 10, "Internet", 1 },
                    { 929, 10, "Magazine", 2 },
                    { 930, 10, "Newspaper", 5 },
                    { 931, 10, "Newspaper", 5 },
                    { 932, 10, "Internet", 1 },
                    { 933, 10, "Magazine", 2 },
                    { 934, 10, "Magazine", 1 },
                    { 935, 10, "Newspaper", 5 },
                    { 923, 10, "Internet", 5 },
                    { 908, 10, "Newspaper", 2 },
                    { 907, 10, "Internet", 2 },
                    { 906, 10, "Magazine", 2 },
                    { 879, 9, "Magazine", 1 },
                    { 880, 9, "Magazine", 3 },
                    { 881, 9, "Newspaper", 3 },
                    { 882, 9, "Magazine", 3 },
                    { 883, 9, "Magazine", 1 },
                    { 884, 9, "App", 4 },
                    { 885, 9, "Magazine", 1 },
                    { 886, 9, "Internet", 2 },
                    { 887, 9, "Newspaper", 3 },
                    { 888, 9, "Internet", 3 },
                    { 889, 9, "App", 2 },
                    { 890, 9, "Internet", 2 },
                    { 891, 9, "App", 1 },
                    { 892, 9, "Magazine", 3 },
                    { 893, 9, "Newspaper", 1 },
                    { 894, 9, "Internet", 3 },
                    { 895, 9, "Magazine", 4 },
                    { 896, 9, "Newspaper", 5 },
                    { 897, 9, "Newspaper", 1 },
                    { 898, 9, "App", 4 },
                    { 899, 9, "Magazine", 3 },
                    { 1, 1, "Magazine", 1 },
                    { 901, 10, "Internet", 5 },
                    { 902, 10, "Internet", 2 },
                    { 903, 10, "Magazine", 1 },
                    { 904, 10, "Internet", 1 },
                    { 905, 10, "App", 1 },
                    { 936, 10, "Internet", 2 },
                    { 937, 10, "Internet", 5 },
                    { 938, 10, "Magazine", 3 },
                    { 939, 10, "Newspaper", 2 },
                    { 971, 10, "App", 2 },
                    { 972, 10, "Internet", 5 },
                    { 973, 10, "App", 1 },
                    { 974, 10, "App", 3 },
                    { 975, 10, "Magazine", 3 },
                    { 976, 10, "Internet", 3 },
                    { 977, 10, "Magazine", 5 },
                    { 978, 10, "Internet", 2 },
                    { 979, 10, "App", 4 },
                    { 980, 10, "Internet", 1 },
                    { 981, 10, "App", 5 },
                    { 982, 10, "Newspaper", 3 },
                    { 983, 10, "Magazine", 5 },
                    { 984, 10, "Newspaper", 5 },
                    { 985, 10, "Internet", 3 },
                    { 986, 10, "Newspaper", 1 },
                    { 987, 10, "Internet", 1 },
                    { 988, 10, "Internet", 3 },
                    { 989, 10, "App", 1 },
                    { 990, 10, "Magazine", 5 },
                    { 991, 10, "Internet", 4 },
                    { 992, 10, "App", 1 },
                    { 993, 10, "Magazine", 5 },
                    { 994, 10, "Newspaper", 2 },
                    { 995, 10, "Newspaper", 2 },
                    { 996, 10, "Internet", 5 },
                    { 997, 10, "Magazine", 5 },
                    { 970, 10, "Internet", 5 },
                    { 878, 9, "Magazine", 3 },
                    { 969, 10, "Internet", 5 },
                    { 967, 10, "Magazine", 5 },
                    { 940, 10, "App", 5 },
                    { 941, 10, "App", 3 },
                    { 942, 10, "Internet", 4 },
                    { 943, 10, "Magazine", 5 },
                    { 944, 10, "App", 4 },
                    { 945, 10, "App", 4 },
                    { 946, 10, "Newspaper", 4 },
                    { 947, 10, "Newspaper", 1 },
                    { 948, 10, "Internet", 4 },
                    { 949, 10, "Internet", 5 },
                    { 950, 10, "Internet", 2 },
                    { 951, 10, "Magazine", 2 },
                    { 952, 10, "Magazine", 5 },
                    { 953, 10, "App", 2 },
                    { 954, 10, "App", 2 },
                    { 955, 10, "Magazine", 5 },
                    { 956, 10, "App", 5 },
                    { 957, 10, "Internet", 5 },
                    { 958, 10, "Internet", 5 },
                    { 959, 10, "App", 3 },
                    { 960, 10, "Magazine", 1 },
                    { 961, 10, "Internet", 5 },
                    { 962, 10, "Internet", 5 },
                    { 963, 10, "Internet", 3 },
                    { 964, 10, "Newspaper", 1 },
                    { 965, 10, "Magazine", 3 },
                    { 966, 10, "Internet", 4 },
                    { 968, 10, "Magazine", 4 },
                    { 877, 9, "App", 2 },
                    { 876, 9, "Magazine", 1 },
                    { 875, 9, "Newspaper", 2 },
                    { 787, 8, "Newspaper", 5 },
                    { 788, 8, "Internet", 5 },
                    { 789, 8, "Internet", 1 },
                    { 790, 8, "Magazine", 1 },
                    { 791, 8, "Internet", 2 },
                    { 792, 8, "Magazine", 2 },
                    { 793, 8, "Newspaper", 1 },
                    { 794, 8, "Magazine", 5 },
                    { 795, 8, "Magazine", 3 },
                    { 796, 8, "Magazine", 5 },
                    { 797, 8, "Internet", 3 },
                    { 798, 8, "App", 4 },
                    { 799, 8, "Magazine", 1 },
                    { 3, 1, "Newspaper", 1 },
                    { 2, 1, "App", 3 },
                    { 801, 9, "Magazine", 1 },
                    { 802, 9, "Magazine", 1 },
                    { 803, 9, "Newspaper", 2 },
                    { 804, 9, "Newspaper", 5 },
                    { 805, 9, "App", 1 },
                    { 806, 9, "Newspaper", 5 },
                    { 807, 9, "Internet", 2 },
                    { 808, 9, "Magazine", 1 },
                    { 809, 9, "Internet", 2 },
                    { 810, 9, "Magazine", 3 },
                    { 811, 9, "Internet", 4 },
                    { 812, 9, "Magazine", 3 },
                    { 786, 8, "App", 2 },
                    { 813, 9, "Internet", 2 },
                    { 785, 8, "Newspaper", 5 },
                    { 783, 8, "Newspaper", 2 },
                    { 756, 8, "App", 2 },
                    { 757, 8, "App", 4 },
                    { 758, 8, "Internet", 5 },
                    { 759, 8, "Magazine", 2 },
                    { 760, 8, "Magazine", 3 },
                    { 761, 8, "Magazine", 4 },
                    { 762, 8, "App", 3 },
                    { 763, 8, "Magazine", 5 },
                    { 764, 8, "Internet", 2 },
                    { 765, 8, "Internet", 5 },
                    { 766, 8, "Internet", 2 },
                    { 767, 8, "Internet", 3 },
                    { 768, 8, "Newspaper", 1 },
                    { 769, 8, "Magazine", 4 },
                    { 770, 8, "Internet", 4 },
                    { 771, 8, "Newspaper", 4 },
                    { 772, 8, "Newspaper", 2 },
                    { 773, 8, "Newspaper", 4 },
                    { 774, 8, "Internet", 2 },
                    { 775, 8, "Internet", 5 },
                    { 776, 8, "App", 1 },
                    { 777, 8, "App", 2 },
                    { 778, 8, "Newspaper", 3 },
                    { 779, 8, "Internet", 2 },
                    { 780, 8, "Magazine", 1 },
                    { 781, 8, "Magazine", 2 },
                    { 782, 8, "App", 2 },
                    { 784, 8, "Magazine", 2 },
                    { 512, 6, "Newspaper", 4 },
                    { 814, 9, "App", 3 },
                    { 816, 9, "Internet", 4 },
                    { 848, 9, "Magazine", 4 },
                    { 849, 9, "App", 5 },
                    { 850, 9, "App", 4 },
                    { 851, 9, "App", 1 },
                    { 852, 9, "Magazine", 4 },
                    { 853, 9, "Newspaper", 4 },
                    { 854, 9, "Magazine", 1 },
                    { 855, 9, "App", 4 },
                    { 856, 9, "Magazine", 2 },
                    { 857, 9, "Internet", 2 },
                    { 858, 9, "Newspaper", 3 },
                    { 859, 9, "Newspaper", 4 },
                    { 860, 9, "App", 4 },
                    { 861, 9, "Newspaper", 1 },
                    { 862, 9, "Internet", 4 },
                    { 863, 9, "Internet", 1 },
                    { 864, 9, "Magazine", 1 },
                    { 865, 9, "Internet", 1 },
                    { 866, 9, "App", 5 },
                    { 867, 9, "Newspaper", 5 },
                    { 868, 9, "App", 1 },
                    { 869, 9, "Magazine", 1 },
                    { 870, 9, "Internet", 5 },
                    { 871, 9, "Internet", 2 },
                    { 872, 9, "App", 1 },
                    { 873, 9, "App", 4 },
                    { 874, 9, "Internet", 5 },
                    { 847, 9, "Magazine", 3 },
                    { 815, 9, "Magazine", 2 },
                    { 846, 9, "Internet", 3 },
                    { 844, 9, "Magazine", 4 },
                    { 817, 9, "Magazine", 1 },
                    { 818, 9, "Magazine", 1 },
                    { 819, 9, "App", 3 },
                    { 820, 9, "Magazine", 5 },
                    { 821, 9, "App", 5 },
                    { 822, 9, "App", 2 },
                    { 823, 9, "Internet", 4 },
                    { 824, 9, "App", 3 },
                    { 825, 9, "App", 2 },
                    { 826, 9, "Newspaper", 5 },
                    { 827, 9, "Newspaper", 2 },
                    { 828, 9, "Internet", 5 },
                    { 829, 9, "Newspaper", 1 },
                    { 830, 9, "Internet", 2 },
                    { 831, 9, "Internet", 5 },
                    { 832, 9, "Newspaper", 5 },
                    { 833, 9, "App", 2 },
                    { 834, 9, "Magazine", 1 },
                    { 835, 9, "Magazine", 1 },
                    { 836, 9, "Newspaper", 1 },
                    { 837, 9, "App", 2 },
                    { 838, 9, "App", 5 },
                    { 839, 9, "Magazine", 4 },
                    { 840, 9, "Internet", 1 },
                    { 841, 9, "Magazine", 4 },
                    { 842, 9, "Magazine", 2 },
                    { 843, 9, "Newspaper", 4 },
                    { 845, 9, "Internet", 5 },
                    { 511, 6, "Newspaper", 1 },
                    { 510, 6, "Magazine", 3 },
                    { 509, 6, "App", 3 },
                    { 173, 2, "Newspaper", 5 },
                    { 174, 2, "Magazine", 4 },
                    { 175, 2, "App", 1 },
                    { 176, 2, "Internet", 1 },
                    { 177, 2, "Internet", 5 },
                    { 178, 2, "Internet", 1 },
                    { 179, 2, "Magazine", 2 },
                    { 180, 2, "App", 4 },
                    { 181, 2, "Magazine", 1 },
                    { 182, 2, "Magazine", 1 },
                    { 183, 2, "Newspaper", 1 },
                    { 184, 2, "Magazine", 5 },
                    { 185, 2, "App", 3 },
                    { 186, 2, "Newspaper", 1 },
                    { 187, 2, "Magazine", 5 },
                    { 188, 2, "Internet", 3 },
                    { 189, 2, "Newspaper", 5 },
                    { 190, 2, "App", 4 },
                    { 191, 2, "Newspaper", 1 },
                    { 192, 2, "Magazine", 1 },
                    { 193, 2, "Magazine", 3 },
                    { 194, 2, "Magazine", 5 },
                    { 195, 2, "Newspaper", 4 },
                    { 196, 2, "App", 1 },
                    { 197, 2, "Magazine", 4 },
                    { 198, 2, "Magazine", 2 },
                    { 199, 2, "Newspaper", 3 },
                    { 172, 2, "Newspaper", 1 },
                    { 14, 1, "Newspaper", 4 },
                    { 171, 2, "Magazine", 2 },
                    { 169, 2, "Newspaper", 3 },
                    { 142, 2, "Internet", 3 },
                    { 143, 2, "Internet", 2 },
                    { 144, 2, "Newspaper", 1 },
                    { 145, 2, "Internet", 3 },
                    { 146, 2, "Internet", 5 },
                    { 147, 2, "Newspaper", 5 },
                    { 148, 2, "App", 3 },
                    { 149, 2, "App", 3 },
                    { 150, 2, "Magazine", 5 },
                    { 151, 2, "Internet", 1 },
                    { 152, 2, "Internet", 2 },
                    { 153, 2, "App", 4 },
                    { 154, 2, "Newspaper", 5 },
                    { 155, 2, "Internet", 2 },
                    { 156, 2, "Magazine", 2 },
                    { 157, 2, "Internet", 3 },
                    { 158, 2, "Magazine", 2 },
                    { 159, 2, "Newspaper", 4 },
                    { 160, 2, "App", 5 },
                    { 161, 2, "App", 4 },
                    { 162, 2, "Magazine", 5 },
                    { 163, 2, "App", 2 },
                    { 164, 2, "Internet", 5 },
                    { 165, 2, "Magazine", 3 },
                    { 166, 2, "App", 5 },
                    { 167, 2, "App", 4 },
                    { 168, 2, "Newspaper", 4 },
                    { 170, 2, "Newspaper", 3 },
                    { 141, 2, "Magazine", 3 },
                    { 201, 3, "Magazine", 2 },
                    { 203, 3, "Internet", 1 },
                    { 235, 3, "App", 5 },
                    { 236, 3, "Newspaper", 2 },
                    { 237, 3, "Magazine", 3 },
                    { 238, 3, "App", 5 },
                    { 239, 3, "Internet", 1 },
                    { 240, 3, "Newspaper", 1 },
                    { 241, 3, "Newspaper", 5 },
                    { 242, 3, "Magazine", 2 },
                    { 243, 3, "Magazine", 1 },
                    { 244, 3, "Newspaper", 5 },
                    { 245, 3, "Newspaper", 3 },
                    { 246, 3, "Internet", 1 },
                    { 247, 3, "Newspaper", 2 },
                    { 248, 3, "App", 4 },
                    { 249, 3, "Newspaper", 2 },
                    { 250, 3, "Newspaper", 1 },
                    { 251, 3, "Newspaper", 1 },
                    { 252, 3, "Internet", 3 },
                    { 253, 3, "Magazine", 4 },
                    { 254, 3, "Internet", 1 },
                    { 255, 3, "Newspaper", 1 },
                    { 256, 3, "App", 4 },
                    { 257, 3, "Magazine", 2 },
                    { 258, 3, "App", 1 },
                    { 259, 3, "Magazine", 3 },
                    { 260, 3, "Magazine", 5 },
                    { 261, 3, "Internet", 5 },
                    { 234, 3, "Magazine", 3 },
                    { 202, 3, "App", 3 },
                    { 233, 3, "App", 2 },
                    { 231, 3, "Magazine", 2 },
                    { 204, 3, "App", 5 },
                    { 205, 3, "Newspaper", 2 },
                    { 206, 3, "Internet", 4 },
                    { 207, 3, "App", 2 },
                    { 208, 3, "Magazine", 5 },
                    { 209, 3, "Magazine", 3 },
                    { 210, 3, "Magazine", 4 },
                    { 211, 3, "Newspaper", 2 },
                    { 212, 3, "Internet", 3 },
                    { 213, 3, "Internet", 5 },
                    { 214, 3, "Internet", 4 },
                    { 215, 3, "Newspaper", 4 },
                    { 216, 3, "App", 1 },
                    { 217, 3, "Magazine", 3 },
                    { 218, 3, "Internet", 1 },
                    { 219, 3, "Internet", 3 },
                    { 220, 3, "App", 2 },
                    { 221, 3, "Magazine", 4 },
                    { 222, 3, "Newspaper", 3 },
                    { 223, 3, "Magazine", 1 },
                    { 224, 3, "Newspaper", 1 },
                    { 225, 3, "App", 5 },
                    { 226, 3, "Magazine", 1 },
                    { 227, 3, "Internet", 5 },
                    { 228, 3, "App", 1 },
                    { 229, 3, "Newspaper", 1 },
                    { 230, 3, "App", 5 },
                    { 232, 3, "Internet", 2 },
                    { 262, 3, "Magazine", 2 },
                    { 140, 2, "App", 3 },
                    { 138, 2, "Magazine", 2 },
                    { 50, 1, "Newspaper", 2 },
                    { 51, 1, "App", 5 },
                    { 52, 1, "Magazine", 2 },
                    { 53, 1, "App", 3 },
                    { 54, 1, "App", 3 },
                    { 55, 1, "Newspaper", 2 },
                    { 56, 1, "Newspaper", 2 },
                    { 57, 1, "Internet", 4 },
                    { 58, 1, "Internet", 4 },
                    { 59, 1, "App", 1 },
                    { 60, 1, "Newspaper", 5 },
                    { 61, 1, "App", 2 },
                    { 62, 1, "Magazine", 2 },
                    { 63, 1, "Internet", 4 },
                    { 64, 1, "Newspaper", 3 },
                    { 65, 1, "App", 1 },
                    { 66, 1, "Newspaper", 3 },
                    { 67, 1, "App", 4 },
                    { 68, 1, "App", 1 },
                    { 69, 1, "Internet", 2 },
                    { 70, 1, "App", 4 },
                    { 71, 1, "Magazine", 1 },
                    { 72, 1, "Newspaper", 4 },
                    { 73, 1, "App", 4 },
                    { 74, 1, "Internet", 1 },
                    { 75, 1, "Magazine", 4 },
                    { 76, 1, "Newspaper", 5 },
                    { 49, 1, "App", 1 },
                    { 77, 1, "App", 5 },
                    { 48, 1, "App", 3 },
                    { 46, 1, "App", 2 },
                    { 19, 1, "Magazine", 4 },
                    { 20, 1, "Internet", 4 },
                    { 21, 1, "Internet", 4 },
                    { 22, 1, "Newspaper", 2 },
                    { 23, 1, "App", 3 },
                    { 24, 1, "Internet", 1 },
                    { 25, 1, "Newspaper", 4 },
                    { 26, 1, "Internet", 3 },
                    { 27, 1, "Internet", 4 },
                    { 28, 1, "Magazine", 2 },
                    { 29, 1, "App", 3 },
                    { 30, 1, "Newspaper", 1 },
                    { 31, 1, "App", 4 },
                    { 32, 1, "Newspaper", 5 },
                    { 33, 1, "App", 5 },
                    { 34, 1, "Internet", 5 },
                    { 35, 1, "Internet", 5 },
                    { 36, 1, "App", 5 },
                    { 37, 1, "Magazine", 4 },
                    { 38, 1, "App", 5 },
                    { 39, 1, "App", 1 },
                    { 40, 1, "App", 1 },
                    { 41, 1, "Magazine", 4 },
                    { 42, 1, "Internet", 4 },
                    { 43, 1, "Newspaper", 3 },
                    { 44, 1, "App", 4 },
                    { 45, 1, "Internet", 5 },
                    { 47, 1, "Newspaper", 2 },
                    { 139, 2, "Magazine", 4 },
                    { 78, 1, "App", 1 },
                    { 80, 1, "Newspaper", 5 },
                    { 111, 2, "Magazine", 3 },
                    { 112, 2, "Internet", 3 },
                    { 113, 2, "Internet", 2 },
                    { 114, 2, "App", 4 },
                    { 115, 2, "App", 3 },
                    { 116, 2, "Magazine", 4 },
                    { 117, 2, "Internet", 5 },
                    { 118, 2, "Internet", 1 },
                    { 119, 2, "App", 5 },
                    { 120, 2, "Magazine", 2 },
                    { 121, 2, "Internet", 5 },
                    { 122, 2, "App", 1 },
                    { 123, 2, "Newspaper", 3 },
                    { 124, 2, "Internet", 3 },
                    { 125, 2, "Newspaper", 2 },
                    { 126, 2, "Newspaper", 4 },
                    { 127, 2, "Magazine", 3 },
                    { 128, 2, "App", 4 },
                    { 129, 2, "App", 2 },
                    { 130, 2, "App", 5 },
                    { 131, 2, "Internet", 1 },
                    { 132, 2, "Internet", 3 },
                    { 133, 2, "App", 5 },
                    { 134, 2, "Newspaper", 2 },
                    { 135, 2, "Newspaper", 5 },
                    { 136, 2, "Magazine", 5 },
                    { 137, 2, "App", 3 },
                    { 110, 2, "Internet", 3 },
                    { 79, 1, "Magazine", 4 },
                    { 109, 2, "App", 3 },
                    { 107, 2, "Internet", 4 },
                    { 81, 1, "Internet", 2 },
                    { 82, 1, "Newspaper", 5 },
                    { 83, 1, "Internet", 5 },
                    { 84, 1, "App", 5 },
                    { 85, 1, "App", 1 },
                    { 86, 1, "App", 4 },
                    { 87, 1, "Internet", 1 },
                    { 88, 1, "App", 3 },
                    { 89, 1, "Magazine", 2 },
                    { 90, 1, "App", 5 },
                    { 91, 1, "Newspaper", 5 },
                    { 92, 1, "Magazine", 3 },
                    { 93, 1, "Internet", 5 },
                    { 94, 1, "App", 3 },
                    { 95, 1, "Internet", 4 },
                    { 96, 1, "App", 1 },
                    { 97, 1, "Internet", 2 },
                    { 98, 1, "App", 3 },
                    { 99, 1, "Internet", 4 },
                    { 16, 1, "Newspaper", 4 },
                    { 15, 1, "Internet", 3 },
                    { 101, 2, "Magazine", 3 },
                    { 102, 2, "Internet", 5 },
                    { 103, 2, "App", 5 },
                    { 104, 2, "App", 5 },
                    { 105, 2, "Magazine", 1 },
                    { 106, 2, "Newspaper", 2 },
                    { 108, 2, "App", 3 },
                    { 263, 3, "Internet", 5 },
                    { 264, 3, "Internet", 1 },
                    { 265, 3, "App", 1 },
                    { 421, 5, "Magazine", 4 },
                    { 422, 5, "App", 4 },
                    { 423, 5, "Magazine", 1 },
                    { 424, 5, "Magazine", 1 },
                    { 425, 5, "Internet", 4 },
                    { 426, 5, "Newspaper", 1 },
                    { 427, 5, "Magazine", 5 },
                    { 428, 5, "Newspaper", 3 },
                    { 429, 5, "Newspaper", 5 },
                    { 430, 5, "Magazine", 5 },
                    { 431, 5, "App", 1 },
                    { 432, 5, "Internet", 4 },
                    { 433, 5, "Newspaper", 5 },
                    { 434, 5, "App", 3 },
                    { 435, 5, "Magazine", 2 },
                    { 436, 5, "App", 3 },
                    { 437, 5, "Internet", 3 },
                    { 438, 5, "App", 3 },
                    { 439, 5, "App", 1 },
                    { 440, 5, "Internet", 5 },
                    { 441, 5, "Magazine", 1 },
                    { 442, 5, "Internet", 3 },
                    { 443, 5, "Magazine", 1 },
                    { 444, 5, "App", 2 },
                    { 445, 5, "Magazine", 2 },
                    { 446, 5, "Newspaper", 2 },
                    { 447, 5, "App", 1 },
                    { 420, 5, "Internet", 2 },
                    { 448, 5, "App", 1 },
                    { 419, 5, "App", 4 },
                    { 417, 5, "App", 3 },
                    { 391, 4, "App", 2 },
                    { 392, 4, "App", 3 },
                    { 393, 4, "App", 4 },
                    { 394, 4, "Magazine", 5 },
                    { 395, 4, "App", 3 },
                    { 396, 4, "Newspaper", 5 },
                    { 397, 4, "Magazine", 3 },
                    { 398, 4, "Internet", 2 },
                    { 399, 4, "Internet", 4 },
                    { 12, 1, "Magazine", 1 },
                    { 11, 1, "Newspaper", 5 },
                    { 401, 5, "Newspaper", 2 },
                    { 402, 5, "Magazine", 2 },
                    { 403, 5, "Newspaper", 4 },
                    { 404, 5, "App", 1 },
                    { 405, 5, "Internet", 1 },
                    { 406, 5, "App", 4 },
                    { 407, 5, "Newspaper", 4 },
                    { 408, 5, "Internet", 3 },
                    { 409, 5, "App", 4 },
                    { 410, 5, "Internet", 2 },
                    { 411, 5, "App", 4 },
                    { 412, 5, "App", 4 },
                    { 413, 5, "Internet", 4 },
                    { 414, 5, "Internet", 2 },
                    { 415, 5, "Internet", 2 },
                    { 416, 5, "Internet", 1 },
                    { 418, 5, "Internet", 5 },
                    { 390, 4, "App", 3 },
                    { 449, 5, "Magazine", 1 },
                    { 451, 5, "Internet", 1 },
                    { 483, 5, "Magazine", 4 },
                    { 484, 5, "Internet", 5 },
                    { 485, 5, "Magazine", 3 },
                    { 486, 5, "Internet", 5 },
                    { 487, 5, "Newspaper", 1 },
                    { 488, 5, "Newspaper", 4 },
                    { 489, 5, "Magazine", 3 },
                    { 490, 5, "Internet", 3 },
                    { 491, 5, "Newspaper", 1 },
                    { 492, 5, "Internet", 3 },
                    { 493, 5, "Newspaper", 2 },
                    { 494, 5, "Magazine", 1 },
                    { 495, 5, "Newspaper", 4 },
                    { 496, 5, "Internet", 1 },
                    { 497, 5, "App", 3 },
                    { 498, 5, "Magazine", 3 },
                    { 499, 5, "Newspaper", 5 },
                    { 10, 1, "Magazine", 5 },
                    { 998, 10, "Newspaper", 1 },
                    { 501, 6, "Magazine", 1 },
                    { 502, 6, "Magazine", 2 },
                    { 503, 6, "Magazine", 5 },
                    { 504, 6, "Internet", 5 },
                    { 505, 6, "Internet", 3 },
                    { 506, 6, "Internet", 5 },
                    { 507, 6, "App", 2 },
                    { 508, 6, "Magazine", 5 },
                    { 482, 5, "Newspaper", 4 },
                    { 450, 5, "Magazine", 5 },
                    { 481, 5, "Internet", 2 },
                    { 479, 5, "Newspaper", 4 },
                    { 452, 5, "Internet", 1 },
                    { 453, 5, "Internet", 4 },
                    { 454, 5, "Magazine", 5 },
                    { 455, 5, "Magazine", 1 },
                    { 456, 5, "App", 2 },
                    { 457, 5, "Magazine", 3 },
                    { 458, 5, "Newspaper", 3 },
                    { 459, 5, "Newspaper", 3 },
                    { 460, 5, "Newspaper", 1 },
                    { 461, 5, "Newspaper", 1 },
                    { 462, 5, "App", 3 },
                    { 463, 5, "Internet", 2 },
                    { 464, 5, "App", 5 },
                    { 465, 5, "Magazine", 5 },
                    { 466, 5, "Magazine", 5 },
                    { 467, 5, "Internet", 5 },
                    { 468, 5, "App", 1 },
                    { 469, 5, "Newspaper", 3 },
                    { 470, 5, "App", 3 },
                    { 471, 5, "Magazine", 4 },
                    { 472, 5, "Magazine", 5 },
                    { 473, 5, "Newspaper", 2 },
                    { 474, 5, "Newspaper", 5 },
                    { 475, 5, "App", 2 },
                    { 476, 5, "Magazine", 2 },
                    { 477, 5, "Newspaper", 3 },
                    { 478, 5, "Magazine", 3 },
                    { 480, 5, "Magazine", 5 },
                    { 389, 4, "Internet", 1 },
                    { 388, 4, "Internet", 2 },
                    { 387, 4, "Newspaper", 4 },
                    { 297, 3, "Magazine", 5 },
                    { 298, 3, "Magazine", 5 },
                    { 299, 3, "App", 3 },
                    { 13, 1, "App", 4 },
                    { 301, 4, "Newspaper", 2 },
                    { 302, 4, "Magazine", 1 },
                    { 303, 4, "App", 1 },
                    { 304, 4, "Internet", 5 },
                    { 305, 4, "Internet", 2 },
                    { 306, 4, "Newspaper", 1 },
                    { 307, 4, "App", 5 },
                    { 308, 4, "Magazine", 5 },
                    { 309, 4, "App", 2 },
                    { 310, 4, "Internet", 1 },
                    { 311, 4, "Internet", 4 },
                    { 312, 4, "Newspaper", 5 },
                    { 313, 4, "Internet", 1 },
                    { 314, 4, "App", 1 },
                    { 315, 4, "App", 3 },
                    { 316, 4, "App", 3 },
                    { 317, 4, "App", 4 },
                    { 318, 4, "Magazine", 5 },
                    { 319, 4, "Magazine", 3 },
                    { 320, 4, "Internet", 3 },
                    { 321, 4, "Newspaper", 2 },
                    { 322, 4, "App", 3 },
                    { 323, 4, "Internet", 3 },
                    { 296, 3, "Internet", 2 },
                    { 324, 4, "Newspaper", 3 },
                    { 295, 3, "Newspaper", 2 },
                    { 293, 3, "App", 3 },
                    { 266, 3, "Magazine", 3 },
                    { 267, 3, "App", 5 },
                    { 268, 3, "Newspaper", 2 },
                    { 269, 3, "Internet", 5 },
                    { 270, 3, "Newspaper", 1 },
                    { 271, 3, "Magazine", 3 },
                    { 272, 3, "Internet", 2 },
                    { 273, 3, "Internet", 3 },
                    { 274, 3, "Magazine", 5 },
                    { 275, 3, "App", 2 },
                    { 276, 3, "Magazine", 3 },
                    { 277, 3, "Newspaper", 3 },
                    { 278, 3, "App", 3 },
                    { 279, 3, "App", 1 },
                    { 280, 3, "Magazine", 2 },
                    { 281, 3, "App", 3 },
                    { 282, 3, "Internet", 2 },
                    { 283, 3, "Internet", 5 },
                    { 284, 3, "Newspaper", 5 },
                    { 285, 3, "Magazine", 3 },
                    { 286, 3, "Newspaper", 5 },
                    { 287, 3, "Newspaper", 3 },
                    { 288, 3, "Internet", 2 },
                    { 289, 3, "Internet", 5 },
                    { 290, 3, "Magazine", 1 },
                    { 291, 3, "Magazine", 1 },
                    { 292, 3, "Internet", 5 },
                    { 294, 3, "Magazine", 1 },
                    { 325, 4, "Newspaper", 1 },
                    { 326, 4, "App", 1 },
                    { 327, 4, "Newspaper", 3 },
                    { 360, 4, "Internet", 4 },
                    { 361, 4, "Magazine", 1 },
                    { 362, 4, "Newspaper", 1 },
                    { 363, 4, "Internet", 5 },
                    { 364, 4, "App", 3 },
                    { 365, 4, "Newspaper", 3 },
                    { 366, 4, "Newspaper", 5 },
                    { 367, 4, "Magazine", 4 },
                    { 368, 4, "Internet", 4 },
                    { 369, 4, "Magazine", 2 },
                    { 370, 4, "Internet", 5 },
                    { 371, 4, "App", 5 },
                    { 372, 4, "Internet", 3 },
                    { 373, 4, "App", 5 },
                    { 374, 4, "Magazine", 5 },
                    { 375, 4, "Magazine", 2 },
                    { 376, 4, "App", 5 },
                    { 377, 4, "Internet", 3 },
                    { 378, 4, "App", 1 },
                    { 379, 4, "Internet", 2 },
                    { 380, 4, "Internet", 1 },
                    { 381, 4, "App", 5 },
                    { 382, 4, "Newspaper", 1 },
                    { 383, 4, "Newspaper", 5 },
                    { 384, 4, "Newspaper", 4 },
                    { 385, 4, "Internet", 5 },
                    { 386, 4, "App", 3 },
                    { 359, 4, "Magazine", 3 },
                    { 358, 4, "App", 2 },
                    { 357, 4, "Magazine", 5 },
                    { 356, 4, "Newspaper", 4 },
                    { 328, 4, "Newspaper", 2 },
                    { 329, 4, "App", 3 },
                    { 330, 4, "App", 3 },
                    { 331, 4, "Internet", 4 },
                    { 332, 4, "Newspaper", 4 },
                    { 333, 4, "Newspaper", 4 },
                    { 334, 4, "App", 4 },
                    { 335, 4, "Internet", 1 },
                    { 336, 4, "Magazine", 5 },
                    { 337, 4, "App", 3 },
                    { 338, 4, "Newspaper", 4 },
                    { 339, 4, "App", 3 },
                    { 340, 4, "App", 5 },
                    { 17, 1, "Internet", 1 },
                    { 341, 4, "App", 4 },
                    { 343, 4, "Newspaper", 4 },
                    { 344, 4, "Internet", 2 },
                    { 345, 4, "Magazine", 4 }
                });

            migrationBuilder.InsertData(
                table: "Ratings",
                columns: new[] { "Id", "ProductionId", "Source", "Stars" },
                values: new object[,]
                {
                    { 346, 4, "App", 2 },
                    { 347, 4, "Magazine", 1 },
                    { 348, 4, "Internet", 3 },
                    { 349, 4, "Internet", 3 },
                    { 350, 4, "Internet", 2 },
                    { 351, 4, "Magazine", 2 },
                    { 352, 4, "Internet", 2 },
                    { 353, 4, "Newspaper", 2 },
                    { 354, 4, "Magazine", 3 },
                    { 355, 4, "Magazine", 4 },
                    { 342, 4, "Internet", 4 },
                    { 999, 10, "Magazine", 2 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Characters_ActorId",
                table: "Characters",
                column: "ActorId");

            migrationBuilder.CreateIndex(
                name: "IX_Characters_ProductionId",
                table: "Characters",
                column: "ProductionId");

            migrationBuilder.CreateIndex(
                name: "IX_Ratings_ProductionId",
                table: "Ratings",
                column: "ProductionId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Characters");

            migrationBuilder.DropTable(
                name: "Ratings");

            migrationBuilder.DropTable(
                name: "Actors");

            migrationBuilder.DropTable(
                name: "Productions");
        }
    }
}
